// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6BAbzFBaWd6-rK_5-mqcglkv_ht3u7g',
    appId: '1:607809773019:web:3af333001d1f5a09875bfe',
    messagingSenderId: '607809773019',
    projectId: 'pomodoro-21e86',
    authDomain: 'pomodoro-21e86.firebaseapp.com',
    storageBucket: 'pomodoro-21e86.appspot.com',
    measurementId: 'G-CTZBD4EWNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5nrWxJs1raHa2lIcUgcuTDaXFmS7EtgA',
    appId: '1:607809773019:android:a9a0b20d7843c42f875bfe',
    messagingSenderId: '607809773019',
    projectId: 'pomodoro-21e86',
    storageBucket: 'pomodoro-21e86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9VmhyGNsPeI0EHX6JRdfazB5CJ_ZlAUI',
    appId: '1:607809773019:ios:224f35bc6706f5dc875bfe',
    messagingSenderId: '607809773019',
    projectId: 'pomodoro-21e86',
    storageBucket: 'pomodoro-21e86.appspot.com',
    iosClientId: '607809773019-13ch5897n23dveed1kdoolvbbojj9g12.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomolab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9VmhyGNsPeI0EHX6JRdfazB5CJ_ZlAUI',
    appId: '1:607809773019:ios:224f35bc6706f5dc875bfe',
    messagingSenderId: '607809773019',
    projectId: 'pomodoro-21e86',
    storageBucket: 'pomodoro-21e86.appspot.com',
    iosClientId: '607809773019-13ch5897n23dveed1kdoolvbbojj9g12.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomolab',
  );
}
